# pyup.io config file
# see https://pyup.io/docs/configuration/ for all available options

branch: dev
schedule: ""
update: all
requirements:
  - localhost/server/requirements.txt:
      update: False
