site_name: "cal-itp/benefits: documentation"
repo_url: https://github.com/cal-itp/benefits
edit_uri: edit/dev/docs
site_url: https://docs.calitp.org/benefits

nav:
  - Home: README.md
  - "Getting started":
      - "Local setup": getting-started/README.md
      - "Development": getting-started/development.md
      - "The localhost directory": getting-started/localhost-directory.md
      - "The test verification server": getting-started/test-verification-server.md
      - "Documentation": getting-started/documentation.md
  - "Token signing & encryption": token-signing-encryption.md
  - Deployment:
      - "The basics": deployment/README.md
      - "Configuration": deployment/configuration.md

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  analytics:
    provider: google
    property: G-SZB618VNBZ

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty
  - fontawesome_markdown
