trigger:
  # automatically runs on pull requests; this runs the pipeline after merge
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers
  branches:
    include:
      - dev
  # only run for changes to Terraform files
  paths:
    include:
      - terraform/*
stages:
  - stage: terraform
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: terraform
        steps:
          # https://github.com/microsoft/azure-pipelines-terraform/tree/main/Tasks/TerraformInstaller#readme
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 1.3.1
          # https://github.com/microsoft/azure-pipelines-terraform/tree/main/Tasks/TerraformTask/TerraformTaskV3#readme
          - task: TerraformTaskV3@3
            displayName: Terraform init
            inputs:
              provider: azurerm
              command: init
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
              # https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#automated-terraform-cli-workflow
              commandOptions: -input=false
              # service connection
              backendServiceArm: Production
              # needs to match main.tf
              backendAzureRmResourceGroupName: RG-CDT-PUB-VIP-CALITP-P-001
              backendAzureRmStorageAccountName: sacdtcalitpp001
              backendAzureRmContainerName: tfstate
              backendAzureRmKey: terraform.tfstate
          - task: TerraformTaskV3@3
            displayName: Terraform plan
            inputs:
              provider: azurerm
              command: plan
              # wait for lock to be released, in case being used by another pipeline run
              # https://discuss.hashicorp.com/t/terraform-plan-wait-for-lock-to-be-released/6870/2
              commandOptions: -input=false -lock-timeout=2m
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
              # service connection
              environmentServiceNameAzureRM: Production
            # the plan is done as part of the apply (below), so don't bother doing it twice
            condition: ne(variables['Build.SourceBranchName'], 'dev')
          - task: TerraformTaskV3@3
            displayName: Terraform apply
            inputs:
              provider: azurerm
              command: apply
              # (ditto the lock comment above)
              commandOptions: -input=false -lock-timeout=2m
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
              # service connection
              environmentServiceNameAzureRM: Production
            # only run on dev
            condition: eq(variables['Build.SourceBranchName'], 'dev')
