name: Deploy (dev)

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/deploy-*.yml'
      - 'benefits/**'
      - 'bin/**'
      - Dockerfile
      - gunicorn.conf.py
      - nginx.conf
      - requirements.txt

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    concurrency: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, tag, and push image to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha,scope=cal-itp
          cache-to: type=gha,scope=cal-itp,mode=max
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:dev
            ghcr.io/${{ github.repository }}:${{ github.sha }}
