name: Publish docs
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/mkdocs.yml'

jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download coverage report
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: tests-pytest.yml
          branch: dev
          event: push
          name: coverage-report
          path: docs/tests/coverage

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          REQUIREMENTS: docs/requirements.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
