name: Pre-commit checks

on:
  pull_request:
    branches: "*"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version-file: .github/workflows/.python-version

      - uses: pre-commit/action@v3.0.0
