name: Pytest

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gettext

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: '**/requirements.txt'
      - name: Install Python dependencies
        run: pip install -r requirements.txt -r tests/pytest/requirements.txt

      - name: Load environment variables
        uses: cardinalby/export-env-action@v1
        with:
          envFile: .devcontainer/.env.sample

      - name: Run setup
        run: ./bin/init.sh

      - name: Run tests
        run: pytest --cov=benefits
